services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile.server
    container_name: backend
    env_file: "./Backend/.env"
    ports:
      - "3001:8080"
    depends_on:
      - db
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile.client
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: postgres:15-alpine
    container_name: db
    env_file: "./Database/.env"
    ports:
      - "5432:5432"
    volumes:
      - ./Database/init/init.sql:/docker-entrypoint-initdb.d/init.sql 
    